version: '3.6'
services:
  postgres:
    image: postgres:10.6
    restart: always
    # Increase max_connections for better dev experience :)
    command: postgres -c 'max_connections=300'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp_development
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build: .
    command: php artisan serve --host=0.0.0.0 --port=3000
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgres
volumes:
  postgres:
